// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/djalben/xplr-core/backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockTicketUseCase is a mock of TicketUseCase interface.
type MockTicketUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTicketUseCaseMockRecorder
}

// MockTicketUseCaseMockRecorder is the mock recorder for MockTicketUseCase.
type MockTicketUseCaseMockRecorder struct {
	mock *MockTicketUseCase
}

// NewMockTicketUseCase creates a new mock instance.
func NewMockTicketUseCase(ctrl *gomock.Controller) *MockTicketUseCase {
	mock := &MockTicketUseCase{ctrl: ctrl}
	mock.recorder = &MockTicketUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketUseCase) EXPECT() *MockTicketUseCaseMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTicketUseCase) Close(ctx context.Context, ticketID domain.UUID, reply string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, ticketID, reply)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTicketUseCaseMockRecorder) Close(ctx, ticketID, reply interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTicketUseCase)(nil).Close), ctx, ticketID, reply)
}

// Create mocks base method.
func (m *MockTicketUseCase) Create(ctx context.Context, userID domain.UUID, subject, message string, tgChatID *int64) (*domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, subject, message, tgChatID)
	ret0, _ := ret[0].(*domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTicketUseCaseMockRecorder) Create(ctx, userID, subject, message, tgChatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTicketUseCase)(nil).Create), ctx, userID, subject, message, tgChatID)
}

// Take mocks base method.
func (m *MockTicketUseCase) Take(ctx context.Context, ticketID, adminID domain.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Take", ctx, ticketID, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Take indicates an expected call of Take.
func (mr *MockTicketUseCaseMockRecorder) Take(ctx, ticketID, adminID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Take", reflect.TypeOf((*MockTicketUseCase)(nil).Take), ctx, ticketID, adminID)
}
