// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/djalben/xplr-core/backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockWalletUseCase is a mock of WalletUseCase interface.
type MockWalletUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockWalletUseCaseMockRecorder
}

// MockWalletUseCaseMockRecorder is the mock recorder for MockWalletUseCase.
type MockWalletUseCaseMockRecorder struct {
	mock *MockWalletUseCase
}

// NewMockWalletUseCase creates a new mock instance.
func NewMockWalletUseCase(ctrl *gomock.Controller) *MockWalletUseCase {
	mock := &MockWalletUseCase{ctrl: ctrl}
	mock.recorder = &MockWalletUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletUseCase) EXPECT() *MockWalletUseCaseMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockWalletUseCase) GetBalance(ctx context.Context, userID domain.UUID) (domain.Numeric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(domain.Numeric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockWalletUseCaseMockRecorder) GetBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockWalletUseCase)(nil).GetBalance), ctx, userID)
}

// ToggleAutoTopUp mocks base method.
func (m *MockWalletUseCase) ToggleAutoTopUp(ctx context.Context, userID domain.UUID, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleAutoTopUp", ctx, userID, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleAutoTopUp indicates an expected call of ToggleAutoTopUp.
func (mr *MockWalletUseCaseMockRecorder) ToggleAutoTopUp(ctx, userID, enabled interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleAutoTopUp", reflect.TypeOf((*MockWalletUseCase)(nil).ToggleAutoTopUp), ctx, userID, enabled)
}

// TopUpWallet mocks base method.
func (m *MockWalletUseCase) TopUpWallet(ctx context.Context, userID domain.UUID, amount domain.Numeric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopUpWallet", ctx, userID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// TopUpWallet indicates an expected call of TopUpWallet.
func (mr *MockWalletUseCaseMockRecorder) TopUpWallet(ctx, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopUpWallet", reflect.TypeOf((*MockWalletUseCase)(nil).TopUpWallet), ctx, userID, amount)
}
