// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/djalben/xplr-core/backend/internal/ports (interfaces: CardRepository,WalletRepository,TransactionRepository,GradeRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/djalben/xplr-core/backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

// MockCardRepository is a mock of CardRepository interface.
type MockCardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCardRepositoryMockRecorder
}

// MockCardRepositoryMockRecorder is the mock recorder for MockCardRepository.
type MockCardRepositoryMockRecorder struct {
	mock *MockCardRepository
}

// NewMockCardRepository creates a new mock instance.
func NewMockCardRepository(ctrl *gomock.Controller) *MockCardRepository {
	mock := &MockCardRepository{ctrl: ctrl}
	mock.recorder = &MockCardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardRepository) EXPECT() *MockCardRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockCardRepository) GetByID(arg0 context.Context, arg1 uuid.UUID) (*domain.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCardRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCardRepository)(nil).GetByID), arg0, arg1)
}

// ListByUserID mocks base method.
func (m *MockCardRepository) ListByUserID(arg0 context.Context, arg1 uuid.UUID) ([]*domain.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockCardRepositoryMockRecorder) ListByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockCardRepository)(nil).ListByUserID), arg0, arg1)
}

// Save mocks base method.
func (m *MockCardRepository) Save(arg0 context.Context, arg1 *domain.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCardRepositoryMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCardRepository)(nil).Save), arg0, arg1)
}

// Update mocks base method.
func (m *MockCardRepository) Update(arg0 context.Context, arg1 *domain.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCardRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCardRepository)(nil).Update), arg0, arg1)
}

// MockWalletRepository is a mock of WalletRepository interface.
type MockWalletRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWalletRepositoryMockRecorder
}

// MockWalletRepositoryMockRecorder is the mock recorder for MockWalletRepository.
type MockWalletRepositoryMockRecorder struct {
	mock *MockWalletRepository
}

// NewMockWalletRepository creates a new mock instance.
func NewMockWalletRepository(ctrl *gomock.Controller) *MockWalletRepository {
	mock := &MockWalletRepository{ctrl: ctrl}
	mock.recorder = &MockWalletRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletRepository) EXPECT() *MockWalletRepositoryMockRecorder {
	return m.recorder
}

// EnsureWallet mocks base method.
func (m *MockWalletRepository) EnsureWallet(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureWallet", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureWallet indicates an expected call of EnsureWallet.
func (mr *MockWalletRepositoryMockRecorder) EnsureWallet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureWallet", reflect.TypeOf((*MockWalletRepository)(nil).EnsureWallet), arg0, arg1)
}

// GetByUserID mocks base method.
func (m *MockWalletRepository) GetByUserID(arg0 context.Context, arg1 uuid.UUID) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockWalletRepositoryMockRecorder) GetByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockWalletRepository)(nil).GetByUserID), arg0, arg1)
}

// Update mocks base method.
func (m *MockWalletRepository) Update(arg0 context.Context, arg1 *domain.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWalletRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWalletRepository)(nil).Update), arg0, arg1)
}

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockTransactionRepository) GetByUserID(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 time.Time, arg4 int) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockTransactionRepositoryMockRecorder) GetByUserID(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockTransactionRepository)(nil).GetByUserID), arg0, arg1, arg2, arg3, arg4)
}

// GetCardTransactions mocks base method.
func (m *MockTransactionRepository) GetCardTransactions(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 time.Time) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardTransactions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCardTransactions indicates an expected call of GetCardTransactions.
func (mr *MockTransactionRepositoryMockRecorder) GetCardTransactions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).GetCardTransactions), arg0, arg1, arg2, arg3)
}

// GetWalletTransactions mocks base method.
func (m *MockTransactionRepository) GetWalletTransactions(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 time.Time) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletTransactions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletTransactions indicates an expected call of GetWalletTransactions.
func (mr *MockTransactionRepositoryMockRecorder) GetWalletTransactions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).GetWalletTransactions), arg0, arg1, arg2, arg3)
}

// Save mocks base method.
func (m *MockTransactionRepository) Save(arg0 context.Context, arg1 *domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockTransactionRepositoryMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTransactionRepository)(nil).Save), arg0, arg1)
}

// SumCardSpendByCardID mocks base method.
func (m *MockTransactionRepository) SumCardSpendByCardID(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 time.Time) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumCardSpendByCardID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumCardSpendByCardID indicates an expected call of SumCardSpendByCardID.
func (mr *MockTransactionRepositoryMockRecorder) SumCardSpendByCardID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumCardSpendByCardID", reflect.TypeOf((*MockTransactionRepository)(nil).SumCardSpendByCardID), arg0, arg1, arg2, arg3)
}

// SumCardSpendByUserAndCardType mocks base method.
func (m *MockTransactionRepository) SumCardSpendByUserAndCardType(arg0 context.Context, arg1 uuid.UUID, arg2 domain.CardType, arg3, arg4 time.Time) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumCardSpendByUserAndCardType", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumCardSpendByUserAndCardType indicates an expected call of SumCardSpendByUserAndCardType.
func (mr *MockTransactionRepositoryMockRecorder) SumCardSpendByUserAndCardType(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumCardSpendByUserAndCardType", reflect.TypeOf((*MockTransactionRepository)(nil).SumCardSpendByUserAndCardType), arg0, arg1, arg2, arg3, arg4)
}

// MockGradeRepository is a mock of GradeRepository interface.
type MockGradeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGradeRepositoryMockRecorder
}

// MockGradeRepositoryMockRecorder is the mock recorder for MockGradeRepository.
type MockGradeRepositoryMockRecorder struct {
	mock *MockGradeRepository
}

// NewMockGradeRepository creates a new mock instance.
func NewMockGradeRepository(ctrl *gomock.Controller) *MockGradeRepository {
	mock := &MockGradeRepository{ctrl: ctrl}
	mock.recorder = &MockGradeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGradeRepository) EXPECT() *MockGradeRepositoryMockRecorder {
	return m.recorder
}

// EnsureGrade mocks base method.
func (m *MockGradeRepository) EnsureGrade(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureGrade", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureGrade indicates an expected call of EnsureGrade.
func (mr *MockGradeRepositoryMockRecorder) EnsureGrade(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureGrade", reflect.TypeOf((*MockGradeRepository)(nil).EnsureGrade), arg0, arg1)
}

// GetByUserID mocks base method.
func (m *MockGradeRepository) GetByUserID(arg0 context.Context, arg1 uuid.UUID) (*domain.UserGrade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].(*domain.UserGrade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockGradeRepositoryMockRecorder) GetByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockGradeRepository)(nil).GetByUserID), arg0, arg1)
}

// Update mocks base method.
func (m *MockGradeRepository) Update(arg0 context.Context, arg1 *domain.UserGrade) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGradeRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGradeRepository)(nil).Update), arg0, arg1)
}
