// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	subscription "github.com/djalben/xplr-core/backend/internal/application/subscription"
	gomock "github.com/golang/mock/gomock"
)

// MockSubscriptionAuthorizationUseCase is a mock of SubscriptionAuthorizationUseCase interface.
type MockSubscriptionAuthorizationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionAuthorizationUseCaseMockRecorder
}

// MockSubscriptionAuthorizationUseCaseMockRecorder is the mock recorder for MockSubscriptionAuthorizationUseCase.
type MockSubscriptionAuthorizationUseCaseMockRecorder struct {
	mock *MockSubscriptionAuthorizationUseCase
}

// NewMockSubscriptionAuthorizationUseCase creates a new mock instance.
func NewMockSubscriptionAuthorizationUseCase(ctrl *gomock.Controller) *MockSubscriptionAuthorizationUseCase {
	mock := &MockSubscriptionAuthorizationUseCase{ctrl: ctrl}
	mock.recorder = &MockSubscriptionAuthorizationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionAuthorizationUseCase) EXPECT() *MockSubscriptionAuthorizationUseCaseMockRecorder {
	return m.recorder
}

// HandleAuthorization mocks base method.
func (m *MockSubscriptionAuthorizationUseCase) HandleAuthorization(arg0 context.Context, arg1 subscription.AuthorizationEvent) (subscription.AuthorizationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleAuthorization", arg0, arg1)
	ret0, _ := ret[0].(subscription.AuthorizationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleAuthorization indicates an expected call of HandleAuthorization.
func (mr *MockSubscriptionAuthorizationUseCaseMockRecorder) HandleAuthorization(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleAuthorization", reflect.TypeOf((*MockSubscriptionAuthorizationUseCase)(nil).HandleAuthorization), arg0, arg1)
}

