// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/djalben/xplr-core/backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSubscriptionUseCase is a mock of SubscriptionUseCase interface.
type MockSubscriptionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionUseCaseMockRecorder
}

// MockSubscriptionUseCaseMockRecorder is the mock recorder for MockSubscriptionUseCase.
type MockSubscriptionUseCaseMockRecorder struct {
	mock *MockSubscriptionUseCase
}

// NewMockSubscriptionUseCase creates a new mock instance.
func NewMockSubscriptionUseCase(ctrl *gomock.Controller) *MockSubscriptionUseCase {
	mock := &MockSubscriptionUseCase{ctrl: ctrl}
	mock.recorder = &MockSubscriptionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionUseCase) EXPECT() *MockSubscriptionUseCaseMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSubscriptionUseCase) List(arg0 context.Context, arg1 uuid.UUID) ([]*domain.CardSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*domain.CardSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSubscriptionUseCaseMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSubscriptionUseCase)(nil).List), arg0, arg1)
}

// SetBlocked mocks base method.
func (m *MockSubscriptionUseCase) SetBlocked(arg0 context.Context, arg1 uuid.UUID, arg2 uuid.UUID, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBlocked", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBlocked indicates an expected call of SetBlocked.
func (mr *MockSubscriptionUseCaseMockRecorder) SetBlocked(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlocked", reflect.TypeOf((*MockSubscriptionUseCase)(nil).SetBlocked), arg0, arg1, arg2, arg3)
}

// SetBlockedByCard mocks base method.
func (m *MockSubscriptionUseCase) SetBlockedByCard(arg0 context.Context, arg1 uuid.UUID, arg2 uuid.UUID, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBlockedByCard", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBlockedByCard indicates an expected call of SetBlockedByCard.
func (mr *MockSubscriptionUseCaseMockRecorder) SetBlockedByCard(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlockedByCard", reflect.TypeOf((*MockSubscriptionUseCase)(nil).SetBlockedByCard), arg0, arg1, arg2, arg3)
}

