// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/djalben/xplr-core/backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockUserProfile is a mock of UserProfile interface.
type MockUserProfile struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileMockRecorder
}

// MockUserProfileMockRecorder is the mock recorder for MockUserProfile.
type MockUserProfileMockRecorder struct {
	mock *MockUserProfile
}

// NewMockUserProfile creates a new mock instance.
func NewMockUserProfile(ctrl *gomock.Controller) *MockUserProfile {
	mock := &MockUserProfile{ctrl: ctrl}
	mock.recorder = &MockUserProfileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfile) EXPECT() *MockUserProfileMockRecorder {
	return m.recorder
}

// GetMe mocks base method.
func (m *MockUserProfile) GetMe(ctx context.Context, userID domain.UUID) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMe", ctx, userID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMe indicates an expected call of GetMe.
func (mr *MockUserProfileMockRecorder) GetMe(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMe", reflect.TypeOf((*MockUserProfile)(nil).GetMe), ctx, userID)
}

// GetReferralInfo mocks base method.
func (m *MockUserProfile) GetReferralInfo(ctx context.Context, userID domain.UUID) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferralInfo", ctx, userID)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferralInfo indicates an expected call of GetReferralInfo.
func (mr *MockUserProfileMockRecorder) GetReferralInfo(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferralInfo", reflect.TypeOf((*MockUserProfile)(nil).GetReferralInfo), ctx, userID)
}

// IssueTelegramLinkCode mocks base method.
func (m *MockUserProfile) IssueTelegramLinkCode(ctx context.Context, userID domain.UUID) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueTelegramLinkCode", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IssueTelegramLinkCode indicates an expected call of IssueTelegramLinkCode.
func (mr *MockUserProfileMockRecorder) IssueTelegramLinkCode(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTelegramLinkCode", reflect.TypeOf((*MockUserProfile)(nil).IssueTelegramLinkCode), ctx, userID)
}

// LinkTelegram mocks base method.
func (m *MockUserProfile) LinkTelegram(ctx context.Context, userID domain.UUID, chatID int64, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkTelegram", ctx, userID, chatID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkTelegram indicates an expected call of LinkTelegram.
func (mr *MockUserProfileMockRecorder) LinkTelegram(ctx, userID, chatID, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkTelegram", reflect.TypeOf((*MockUserProfile)(nil).LinkTelegram), ctx, userID, chatID, code)
}

// SetNotificationPreferences mocks base method.
func (m *MockUserProfile) SetNotificationPreferences(ctx context.Context, userID domain.UUID, notifyEmail, notifyTelegram bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNotificationPreferences", ctx, userID, notifyEmail, notifyTelegram)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNotificationPreferences indicates an expected call of SetNotificationPreferences.
func (mr *MockUserProfileMockRecorder) SetNotificationPreferences(ctx, userID, notifyEmail, notifyTelegram interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNotificationPreferences", reflect.TypeOf((*MockUserProfile)(nil).SetNotificationPreferences), ctx, userID, notifyEmail, notifyTelegram)
}

// MockKYCApplications is a mock of KYCApplications interface.
type MockKYCApplications struct {
	ctrl     *gomock.Controller
	recorder *MockKYCApplicationsMockRecorder
}

// MockKYCApplicationsMockRecorder is the mock recorder for MockKYCApplications.
type MockKYCApplicationsMockRecorder struct {
	mock *MockKYCApplications
}

// NewMockKYCApplications creates a new mock instance.
func NewMockKYCApplications(ctrl *gomock.Controller) *MockKYCApplications {
	mock := &MockKYCApplications{ctrl: ctrl}
	mock.recorder = &MockKYCApplicationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKYCApplications) EXPECT() *MockKYCApplicationsMockRecorder {
	return m.recorder
}

// SubmitApplication mocks base method.
func (m *MockKYCApplications) SubmitApplication(ctx context.Context, userID domain.UUID, payloadJSON string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitApplication", ctx, userID, payloadJSON)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitApplication indicates an expected call of SubmitApplication.
func (mr *MockKYCApplicationsMockRecorder) SubmitApplication(ctx, userID, payloadJSON interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitApplication", reflect.TypeOf((*MockKYCApplications)(nil).SubmitApplication), ctx, userID, payloadJSON)
}

// MockTOTPSettings is a mock of TOTPSettings interface.
type MockTOTPSettings struct {
	ctrl     *gomock.Controller
	recorder *MockTOTPSettingsMockRecorder
}

// MockTOTPSettingsMockRecorder is the mock recorder for MockTOTPSettings.
type MockTOTPSettingsMockRecorder struct {
	mock *MockTOTPSettings
}

// NewMockTOTPSettings creates a new mock instance.
func NewMockTOTPSettings(ctrl *gomock.Controller) *MockTOTPSettings {
	mock := &MockTOTPSettings{ctrl: ctrl}
	mock.recorder = &MockTOTPSettingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTOTPSettings) EXPECT() *MockTOTPSettingsMockRecorder {
	return m.recorder
}

// ConfirmTOTP mocks base method.
func (m *MockTOTPSettings) ConfirmTOTP(ctx context.Context, userID domain.UUID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmTOTP", ctx, userID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmTOTP indicates an expected call of ConfirmTOTP.
func (mr *MockTOTPSettingsMockRecorder) ConfirmTOTP(ctx, userID, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmTOTP", reflect.TypeOf((*MockTOTPSettings)(nil).ConfirmTOTP), ctx, userID, code)
}

// DisableTOTP mocks base method.
func (m *MockTOTPSettings) DisableTOTP(ctx context.Context, userID domain.UUID, password, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableTOTP", ctx, userID, password, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableTOTP indicates an expected call of DisableTOTP.
func (mr *MockTOTPSettingsMockRecorder) DisableTOTP(ctx, userID, password, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableTOTP", reflect.TypeOf((*MockTOTPSettings)(nil).DisableTOTP), ctx, userID, password, code)
}

// SetupTOTP mocks base method.
func (m *MockTOTPSettings) SetupTOTP(ctx context.Context, userID domain.UUID) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupTOTP", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetupTOTP indicates an expected call of SetupTOTP.
func (mr *MockTOTPSettingsMockRecorder) SetupTOTP(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupTOTP", reflect.TypeOf((*MockTOTPSettings)(nil).SetupTOTP), ctx, userID)
}

// MockUserWallet is a mock of UserWallet interface.
type MockUserWallet struct {
	ctrl     *gomock.Controller
	recorder *MockUserWalletMockRecorder
}

// MockUserWalletMockRecorder is the mock recorder for MockUserWallet.
type MockUserWalletMockRecorder struct {
	mock *MockUserWallet
}

// NewMockUserWallet creates a new mock instance.
func NewMockUserWallet(ctrl *gomock.Controller) *MockUserWallet {
	mock := &MockUserWallet{ctrl: ctrl}
	mock.recorder = &MockUserWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserWallet) EXPECT() *MockUserWalletMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockUserWallet) GetBalance(ctx context.Context, userID domain.UUID) (domain.Numeric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(domain.Numeric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockUserWalletMockRecorder) GetBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockUserWallet)(nil).GetBalance), ctx, userID)
}

// GetAutoTopUpEnabled mocks base method.
func (m *MockUserWallet) GetAutoTopUpEnabled(ctx context.Context, userID domain.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutoTopUpEnabled", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutoTopUpEnabled indicates an expected call of GetAutoTopUpEnabled.
func (mr *MockUserWalletMockRecorder) GetAutoTopUpEnabled(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutoTopUpEnabled", reflect.TypeOf((*MockUserWallet)(nil).GetAutoTopUpEnabled), ctx, userID)
}

// ToggleAutoTopUp mocks base method.
func (m *MockUserWallet) ToggleAutoTopUp(ctx context.Context, userID domain.UUID, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleAutoTopUp", ctx, userID, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleAutoTopUp indicates an expected call of ToggleAutoTopUp.
func (mr *MockUserWalletMockRecorder) ToggleAutoTopUp(ctx, userID, enabled interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleAutoTopUp", reflect.TypeOf((*MockUserWallet)(nil).ToggleAutoTopUp), ctx, userID, enabled)
}

// TopUpWallet mocks base method.
func (m *MockUserWallet) TopUpWallet(ctx context.Context, userID domain.UUID, amount domain.Numeric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopUpWallet", ctx, userID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// TopUpWallet indicates an expected call of TopUpWallet.
func (mr *MockUserWalletMockRecorder) TopUpWallet(ctx, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopUpWallet", reflect.TypeOf((*MockUserWallet)(nil).TopUpWallet), ctx, userID, amount)
}

// MockUserGrades is a mock of UserGrades interface.
type MockUserGrades struct {
	ctrl     *gomock.Controller
	recorder *MockUserGradesMockRecorder
}

// MockUserGradesMockRecorder is the mock recorder for MockUserGrades.
type MockUserGradesMockRecorder struct {
	mock *MockUserGrades
}

// NewMockUserGrades creates a new mock instance.
func NewMockUserGrades(ctrl *gomock.Controller) *MockUserGrades {
	mock := &MockUserGrades{ctrl: ctrl}
	mock.recorder = &MockUserGradesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserGrades) EXPECT() *MockUserGradesMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockUserGrades) GetByUserID(ctx context.Context, userID domain.UUID) (*domain.UserGrade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.UserGrade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserGradesMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserGrades)(nil).GetByUserID), ctx, userID)
}

// MockUserCards is a mock of UserCards interface.
type MockUserCards struct {
	ctrl     *gomock.Controller
	recorder *MockUserCardsMockRecorder
}

// MockUserCardsMockRecorder is the mock recorder for MockUserCards.
type MockUserCardsMockRecorder struct {
	mock *MockUserCards
}

// NewMockUserCards creates a new mock instance.
func NewMockUserCards(ctrl *gomock.Controller) *MockUserCards {
	mock := &MockUserCards{ctrl: ctrl}
	mock.recorder = &MockUserCardsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCards) EXPECT() *MockUserCardsMockRecorder {
	return m.recorder
}

// BuyCard mocks base method.
func (m *MockUserCards) BuyCard(ctx context.Context, userID domain.UUID, cardType domain.CardType, nickname string) (*domain.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuyCard", ctx, userID, cardType, nickname)
	ret0, _ := ret[0].(*domain.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuyCard indicates an expected call of BuyCard.
func (mr *MockUserCardsMockRecorder) BuyCard(ctx, userID, cardType, nickname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuyCard", reflect.TypeOf((*MockUserCards)(nil).BuyCard), ctx, userID, cardType, nickname)
}

// GetByID mocks base method.
func (m *MockUserCards) GetByID(ctx context.Context, cardID domain.UUID) (*domain.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, cardID)
	ret0, _ := ret[0].(*domain.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserCardsMockRecorder) GetByID(ctx, cardID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserCards)(nil).GetByID), ctx, cardID)
}

// ListByUserID mocks base method.
func (m *MockUserCards) ListByUserID(ctx context.Context, userID domain.UUID) ([]*domain.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockUserCardsMockRecorder) ListByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockUserCards)(nil).ListByUserID), ctx, userID)
}

// RecordFailedAuthorization mocks base method.
func (m *MockUserCards) RecordFailedAuthorization(ctx context.Context, userID, cardID domain.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFailedAuthorization", ctx, userID, cardID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordFailedAuthorization indicates an expected call of RecordFailedAuthorization.
func (mr *MockUserCardsMockRecorder) RecordFailedAuthorization(ctx, userID, cardID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFailedAuthorization", reflect.TypeOf((*MockUserCards)(nil).RecordFailedAuthorization), ctx, userID, cardID)
}

// SetSpendingLimit mocks base method.
func (m *MockUserCards) SetSpendingLimit(ctx context.Context, userID, cardID domain.UUID, limit domain.Numeric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSpendingLimit", ctx, userID, cardID, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSpendingLimit indicates an expected call of SetSpendingLimit.
func (mr *MockUserCardsMockRecorder) SetSpendingLimit(ctx, userID, cardID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSpendingLimit", reflect.TypeOf((*MockUserCards)(nil).SetSpendingLimit), ctx, userID, cardID, limit)
}

// SpendFromCard mocks base method.
func (m *MockUserCards) SpendFromCard(ctx context.Context, userID, cardID domain.UUID, amount domain.Numeric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpendFromCard", ctx, userID, cardID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// SpendFromCard indicates an expected call of SpendFromCard.
func (mr *MockUserCardsMockRecorder) SpendFromCard(ctx, userID, cardID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpendFromCard", reflect.TypeOf((*MockUserCards)(nil).SpendFromCard), ctx, userID, cardID, amount)
}

// TopUpCard mocks base method.
func (m *MockUserCards) TopUpCard(ctx context.Context, userID, cardID domain.UUID, amount domain.Numeric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopUpCard", ctx, userID, cardID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// TopUpCard indicates an expected call of TopUpCard.
func (mr *MockUserCardsMockRecorder) TopUpCard(ctx, userID, cardID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopUpCard", reflect.TypeOf((*MockUserCards)(nil).TopUpCard), ctx, userID, cardID, amount)
}

// UpdateStatus mocks base method.
func (m *MockUserCards) UpdateStatus(ctx context.Context, userID, cardID domain.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, userID, cardID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockUserCardsMockRecorder) UpdateStatus(ctx, userID, cardID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockUserCards)(nil).UpdateStatus), ctx, userID, cardID, status)
}

// MockUserTransactions is a mock of UserTransactions interface.
type MockUserTransactions struct {
	ctrl     *gomock.Controller
	recorder *MockUserTransactionsMockRecorder
}

// MockUserTransactionsMockRecorder is the mock recorder for MockUserTransactions.
type MockUserTransactionsMockRecorder struct {
	mock *MockUserTransactions
}

// NewMockUserTransactions creates a new mock instance.
func NewMockUserTransactions(ctrl *gomock.Controller) *MockUserTransactions {
	mock := &MockUserTransactions{ctrl: ctrl}
	mock.recorder = &MockUserTransactionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserTransactions) EXPECT() *MockUserTransactionsMockRecorder {
	return m.recorder
}

// GetUnifiedTransactions mocks base method.
func (m *MockUserTransactions) GetUnifiedTransactions(ctx context.Context, userID domain.UUID, from, to time.Time, limit int) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnifiedTransactions", ctx, userID, from, to, limit)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnifiedTransactions indicates an expected call of GetUnifiedTransactions.
func (mr *MockUserTransactionsMockRecorder) GetUnifiedTransactions(ctx, userID, from, to, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnifiedTransactions", reflect.TypeOf((*MockUserTransactions)(nil).GetUnifiedTransactions), ctx, userID, from, to, limit)
}

// MockUserTickets is a mock of UserTickets interface.
type MockUserTickets struct {
	ctrl     *gomock.Controller
	recorder *MockUserTicketsMockRecorder
}

// MockUserTicketsMockRecorder is the mock recorder for MockUserTickets.
type MockUserTicketsMockRecorder struct {
	mock *MockUserTickets
}

// NewMockUserTickets creates a new mock instance.
func NewMockUserTickets(ctrl *gomock.Controller) *MockUserTickets {
	mock := &MockUserTickets{ctrl: ctrl}
	mock.recorder = &MockUserTicketsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserTickets) EXPECT() *MockUserTicketsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserTickets) Create(ctx context.Context, userID domain.UUID, subject, message string, tgChatID *int64) (*domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, subject, message, tgChatID)
	ret0, _ := ret[0].(*domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserTicketsMockRecorder) Create(ctx, userID, subject, message, tgChatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserTickets)(nil).Create), ctx, userID, subject, message, tgChatID)
}
