// Code generated by MockGen-style template. DO NOT EDIT.
// Source: github.com/djalben/xplr-core/backend/internal/ports (interface: CardSubscriptionRepository)

package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/djalben/xplr-core/backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

// MockCardSubscriptionRepository is a mock of CardSubscriptionRepository interface.
type MockCardSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCardSubscriptionRepositoryMockRecorder
}

// MockCardSubscriptionRepositoryMockRecorder is the mock recorder for MockCardSubscriptionRepository.
type MockCardSubscriptionRepositoryMockRecorder struct {
	mock *MockCardSubscriptionRepository
}

// NewMockCardSubscriptionRepository creates a new mock instance.
func NewMockCardSubscriptionRepository(ctrl *gomock.Controller) *MockCardSubscriptionRepository {
	mock := &MockCardSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockCardSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardSubscriptionRepository) EXPECT() *MockCardSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// UpsertOnCharge mocks base method.
func (m *MockCardSubscriptionRepository) UpsertOnCharge(arg0 context.Context, arg1 uuid.UUID, arg2 uuid.UUID, arg3 string, arg4 decimal.Decimal, arg5 string, arg6 time.Time) (*domain.CardSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertOnCharge", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*domain.CardSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertOnCharge indicates an expected call of UpsertOnCharge.
func (mr *MockCardSubscriptionRepositoryMockRecorder) UpsertOnCharge(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertOnCharge", reflect.TypeOf((*MockCardSubscriptionRepository)(nil).UpsertOnCharge), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// ListByUserID mocks base method.
func (m *MockCardSubscriptionRepository) ListByUserID(arg0 context.Context, arg1 uuid.UUID) ([]*domain.CardSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", arg0, arg1)
	ret0, _ := ret[0].([]*domain.CardSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockCardSubscriptionRepositoryMockRecorder) ListByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockCardSubscriptionRepository)(nil).ListByUserID), arg0, arg1)
}

// SetBlocked mocks base method.
func (m *MockCardSubscriptionRepository) SetBlocked(arg0 context.Context, arg1 uuid.UUID, arg2 uuid.UUID, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBlocked", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBlocked indicates an expected call of SetBlocked.
func (mr *MockCardSubscriptionRepositoryMockRecorder) SetBlocked(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlocked", reflect.TypeOf((*MockCardSubscriptionRepository)(nil).SetBlocked), arg0, arg1, arg2, arg3)
}

// SetBlockedByCardID mocks base method.
func (m *MockCardSubscriptionRepository) SetBlockedByCardID(arg0 context.Context, arg1 uuid.UUID, arg2 uuid.UUID, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBlockedByCardID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBlockedByCardID indicates an expected call of SetBlockedByCardID.
func (mr *MockCardSubscriptionRepositoryMockRecorder) SetBlockedByCardID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlockedByCardID", reflect.TypeOf((*MockCardSubscriptionRepository)(nil).SetBlockedByCardID), arg0, arg1, arg2, arg3)
}

// GetByCardAndMerchantKey mocks base method.
func (m *MockCardSubscriptionRepository) GetByCardAndMerchantKey(arg0 context.Context, arg1 uuid.UUID, arg2 string) (*domain.CardSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCardAndMerchantKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.CardSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCardAndMerchantKey indicates an expected call of GetByCardAndMerchantKey.
func (mr *MockCardSubscriptionRepositoryMockRecorder) GetByCardAndMerchantKey(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCardAndMerchantKey", reflect.TypeOf((*MockCardSubscriptionRepository)(nil).GetByCardAndMerchantKey), arg0, arg1, arg2)
}

