// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	auth "github.com/djalben/xplr-core/backend/internal/application/auth"
	domain "github.com/djalben/xplr-core/backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthFlow is a mock of AuthFlow interface.
type MockAuthFlow struct {
	ctrl     *gomock.Controller
	recorder *MockAuthFlowMockRecorder
}

// MockAuthFlowMockRecorder is the mock recorder for MockAuthFlow.
type MockAuthFlowMockRecorder struct {
	mock *MockAuthFlow
}

// NewMockAuthFlow creates a new mock instance.
func NewMockAuthFlow(ctrl *gomock.Controller) *MockAuthFlow {
	mock := &MockAuthFlow{ctrl: ctrl}
	mock.recorder = &MockAuthFlowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthFlow) EXPECT() *MockAuthFlowMockRecorder {
	return m.recorder
}

// CompleteMFALogin mocks base method.
func (m *MockAuthFlow) CompleteMFALogin(ctx context.Context, mfaToken, totpCode string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMFALogin", ctx, mfaToken, totpCode)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteMFALogin indicates an expected call of CompleteMFALogin.
func (mr *MockAuthFlowMockRecorder) CompleteMFALogin(ctx, mfaToken, totpCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMFALogin", reflect.TypeOf((*MockAuthFlow)(nil).CompleteMFALogin), ctx, mfaToken, totpCode)
}

// Login mocks base method.
func (m *MockAuthFlow) Login(ctx context.Context, email, password string) (*auth.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*auth.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthFlowMockRecorder) Login(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthFlow)(nil).Login), ctx, email, password)
}

// LoginWithTrustedDevice mocks base method.
func (m *MockAuthFlow) LoginWithTrustedDevice(ctx context.Context, email, password, trustedDeviceToken string, now time.Time) (*auth.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginWithTrustedDevice", ctx, email, password, trustedDeviceToken, now)
	ret0, _ := ret[0].(*auth.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginWithTrustedDevice indicates an expected call of LoginWithTrustedDevice.
func (mr *MockAuthFlowMockRecorder) LoginWithTrustedDevice(ctx, email, password, trustedDeviceToken, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginWithTrustedDevice", reflect.TypeOf((*MockAuthFlow)(nil).LoginWithTrustedDevice), ctx, email, password, trustedDeviceToken, now)
}

// RememberTrustedDevice mocks base method.
func (m *MockAuthFlow) RememberTrustedDevice(ctx context.Context, userID domain.UUID, userAgent string, ip *string, now time.Time) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RememberTrustedDevice", ctx, userID, userAgent, ip, now)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RememberTrustedDevice indicates an expected call of RememberTrustedDevice.
func (mr *MockAuthFlowMockRecorder) RememberTrustedDevice(ctx, userID, userAgent, ip, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RememberTrustedDevice", reflect.TypeOf((*MockAuthFlow)(nil).RememberTrustedDevice), ctx, userID, userAgent, ip, now)
}

// Register mocks base method.
func (m *MockAuthFlow) Register(ctx context.Context, email, password string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, email, password)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthFlowMockRecorder) Register(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthFlow)(nil).Register), ctx, email, password)
}

// RequestPasswordReset mocks base method.
func (m *MockAuthFlow) RequestPasswordReset(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestPasswordReset", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestPasswordReset indicates an expected call of RequestPasswordReset.
func (mr *MockAuthFlowMockRecorder) RequestPasswordReset(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestPasswordReset", reflect.TypeOf((*MockAuthFlow)(nil).RequestPasswordReset), ctx, email)
}

// ResetPassword mocks base method.
func (m *MockAuthFlow) ResetPassword(ctx context.Context, token, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, token, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockAuthFlowMockRecorder) ResetPassword(ctx, token, newPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockAuthFlow)(nil).ResetPassword), ctx, token, newPassword)
}

// VerifyEmail mocks base method.
func (m *MockAuthFlow) VerifyEmail(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockAuthFlowMockRecorder) VerifyEmail(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockAuthFlow)(nil).VerifyEmail), ctx, token)
}

// MockWalletBalanceProvider is a mock of WalletBalanceProvider interface.
type MockWalletBalanceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockWalletBalanceProviderMockRecorder
}

// MockWalletBalanceProviderMockRecorder is the mock recorder for MockWalletBalanceProvider.
type MockWalletBalanceProviderMockRecorder struct {
	mock *MockWalletBalanceProvider
}

// NewMockWalletBalanceProvider creates a new mock instance.
func NewMockWalletBalanceProvider(ctrl *gomock.Controller) *MockWalletBalanceProvider {
	mock := &MockWalletBalanceProvider{ctrl: ctrl}
	mock.recorder = &MockWalletBalanceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletBalanceProvider) EXPECT() *MockWalletBalanceProviderMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockWalletBalanceProvider) GetBalance(ctx context.Context, userID domain.UUID) (domain.Numeric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(domain.Numeric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockWalletBalanceProviderMockRecorder) GetBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockWalletBalanceProvider)(nil).GetBalance), ctx, userID)
}

// MockUserByIDReader is a mock of UserByIDReader interface.
type MockUserByIDReader struct {
	ctrl     *gomock.Controller
	recorder *MockUserByIDReaderMockRecorder
}

// MockUserByIDReaderMockRecorder is the mock recorder for MockUserByIDReader.
type MockUserByIDReaderMockRecorder struct {
	mock *MockUserByIDReader
}

// NewMockUserByIDReader creates a new mock instance.
func NewMockUserByIDReader(ctrl *gomock.Controller) *MockUserByIDReader {
	mock := &MockUserByIDReader{ctrl: ctrl}
	mock.recorder = &MockUserByIDReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserByIDReader) EXPECT() *MockUserByIDReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserByIDReader) GetByID(ctx context.Context, id domain.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserByIDReaderMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserByIDReader)(nil).GetByID), ctx, id)
}

// SetLastLogin mocks base method.
func (m *MockUserByIDReader) SetLastLogin(ctx context.Context, id domain.UUID, at time.Time, ip *string, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastLogin", ctx, id, at, ip, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastLogin indicates an expected call of SetLastLogin.
func (mr *MockUserByIDReaderMockRecorder) SetLastLogin(ctx, id, at, ip, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastLogin", reflect.TypeOf((*MockUserByIDReader)(nil).SetLastLogin), ctx, id, at, ip, userAgent)
}
