// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/djalben/xplr-core/backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthRegisterLogin is a mock of AuthRegisterLogin interface.
type MockAuthRegisterLogin struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRegisterLoginMockRecorder
}

// MockAuthRegisterLoginMockRecorder is the mock recorder for MockAuthRegisterLogin.
type MockAuthRegisterLoginMockRecorder struct {
	mock *MockAuthRegisterLogin
}

// NewMockAuthRegisterLogin creates a new mock instance.
func NewMockAuthRegisterLogin(ctrl *gomock.Controller) *MockAuthRegisterLogin {
	mock := &MockAuthRegisterLogin{ctrl: ctrl}
	mock.recorder = &MockAuthRegisterLoginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRegisterLogin) EXPECT() *MockAuthRegisterLoginMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthRegisterLogin) Login(ctx context.Context, email, password string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthRegisterLoginMockRecorder) Login(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthRegisterLogin)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockAuthRegisterLogin) Register(ctx context.Context, email, password string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, email, password)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthRegisterLoginMockRecorder) Register(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthRegisterLogin)(nil).Register), ctx, email, password)
}

// MockWalletBalanceProvider is a mock of WalletBalanceProvider interface.
type MockWalletBalanceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockWalletBalanceProviderMockRecorder
}

// MockWalletBalanceProviderMockRecorder is the mock recorder for MockWalletBalanceProvider.
type MockWalletBalanceProviderMockRecorder struct {
	mock *MockWalletBalanceProvider
}

// NewMockWalletBalanceProvider creates a new mock instance.
func NewMockWalletBalanceProvider(ctrl *gomock.Controller) *MockWalletBalanceProvider {
	mock := &MockWalletBalanceProvider{ctrl: ctrl}
	mock.recorder = &MockWalletBalanceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletBalanceProvider) EXPECT() *MockWalletBalanceProviderMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockWalletBalanceProvider) GetBalance(ctx context.Context, userID domain.UUID) (domain.Numeric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(domain.Numeric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockWalletBalanceProviderMockRecorder) GetBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockWalletBalanceProvider)(nil).GetBalance), ctx, userID)
}

// MockUserByIDReader is a mock of UserByIDReader interface.
type MockUserByIDReader struct {
	ctrl     *gomock.Controller
	recorder *MockUserByIDReaderMockRecorder
}

// MockUserByIDReaderMockRecorder is the mock recorder for MockUserByIDReader.
type MockUserByIDReaderMockRecorder struct {
	mock *MockUserByIDReader
}

// NewMockUserByIDReader creates a new mock instance.
func NewMockUserByIDReader(ctrl *gomock.Controller) *MockUserByIDReader {
	mock := &MockUserByIDReader{ctrl: ctrl}
	mock.recorder = &MockUserByIDReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserByIDReader) EXPECT() *MockUserByIDReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserByIDReader) GetByID(ctx context.Context, id domain.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserByIDReaderMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserByIDReader)(nil).GetByID), ctx, id)
}
