package providers

// countryNameToISO maps Keepgo coverage country names (English) to ISO-3166-1
// alpha-2 codes. Used to resolve regional bundle coverage into flagged
// destinations. Includes common variants/spellings used by the Keepgo API.
var countryNameToISO = map[string]string{
	"Afghanistan":                                  "AF",
	"Albania":                                       "AL",
	"Algeria":                                       "DZ",
	"Andorra":                                       "AD",
	"Angola":                                        "AO",
	"Anguilla":                                      "AI",
	"Antigua and Barbuda":                           "AG",
	"Argentina":                                     "AR",
	"Armenia":                                       "AM",
	"Aruba":                                         "AW",
	"Australia":                                     "AU",
	"Austria":                                       "AT",
	"Azerbaijan":                                    "AZ",
	"Bahamas":                                        "BS",
	"Bahrain":                                        "BH",
	"Bangladesh":                                     "BD",
	"Barbados":                                       "BB",
	"Belarus":                                        "BY",
	"Belgium":                                        "BE",
	"Belize":                                         "BZ",
	"Benin":                                          "BJ",
	"Bermuda":                                        "BM",
	"Bhutan":                                         "BT",
	"Bolivia":                                        "BO",
	"Bosnia and Herzegovina":                         "BA",
	"Botswana":                                       "BW",
	"Brazil":                                         "BR",
	"Brunei":                                         "BN",
	"Brunei Darussalam":                              "BN",
	"Bulgaria":                                       "BG",
	"Burkina Faso":                                   "BF",
	"Cambodia":                                       "KH",
	"Cameroon":                                       "CM",
	"Canada":                                         "CA",
	"Cape Verde":                                     "CV",
	"Cayman Islands":                                 "KY",
	"Chad":                                           "TD",
	"Chile":                                          "CL",
	"China":                                          "CN",
	"Colombia":                                       "CO",
	"Congo":                                          "CG",
	"Costa Rica":                                     "CR",
	"Croatia":                                        "HR",
	"Cyprus":                                         "CY",
	"Czech Republic":                                 "CZ",
	"Czechia":                                        "CZ",
	"Denmark":                                        "DK",
	"Dominica":                                       "DM",
	"Dominican Republic":                             "DO",
	"Ecuador":                                        "EC",
	"Egypt":                                          "EG",
	"El Salvador":                                    "SV",
	"Estonia":                                        "EE",
	"Eswatini":                                       "SZ",
	"Ethiopia":                                       "ET",
	"Fiji":                                           "FJ",
	"Finland":                                        "FI",
	"France":                                         "FR",
	"French Guiana":                                  "GF",
	"Gabon":                                          "GA",
	"Georgia":                                        "GE",
	"Germany":                                        "DE",
	"Ghana":                                          "GH",
	"Gibraltar":                                      "GI",
	"Greece":                                         "GR",
	"Greenland":                                      "GL",
	"Grenada":                                        "GD",
	"Guadeloupe":                                     "GP",
	"Guam":                                           "GU",
	"Guatemala":                                      "GT",
	"Guernsey":                                       "GG",
	"Guyana":                                         "GY",
	"Honduras":                                       "HN",
	"Hong Kong":                                      "HK",
	"Hungary":                                        "HU",
	"Iceland":                                        "IS",
	"India":                                          "IN",
	"Indonesia":                                      "ID",
	"Iran":                                           "IR",
	"Iraq":                                           "IQ",
	"Ireland":                                        "IE",
	"Isle of Man":                                    "IM",
	"Israel":                                         "IL",
	"Italy":                                          "IT",
	"Ivory Coast":                                    "CI",
	"Jamaica":                                        "JM",
	"Japan":                                          "JP",
	"Jersey":                                         "JE",
	"Jordan":                                         "JO",
	"Kazakhstan":                                     "KZ",
	"Kenya":                                          "KE",
	"Kosovo":                                         "XK",
	"Kuwait":                                         "KW",
	"Kyrgyzstan":                                     "KG",
	"Lao People's Democratic Republic":              "LA",
	"Laos":                                           "LA",
	"Latvia":                                         "LV",
	"Lebanon":                                        "LB",
	"Liechtenstein":                                  "LI",
	"Lithuania":                                      "LT",
	"Luxembourg":                                     "LU",
	"Macao":                                          "MO",
	"Macau":                                          "MO",
	"Madagascar":                                     "MG",
	"Malawi":                                         "MW",
	"Malaysia":                                       "MY",
	"Maldives":                                       "MV",
	"Mali":                                           "ML",
	"Malta":                                          "MT",
	"Martinique":                                     "MQ",
	"Mauritius":                                      "MU",
	"Mexico":                                         "MX",
	"Moldova":                                        "MD",
	"Monaco":                                         "MC",
	"Mongolia":                                       "MN",
	"Montenegro":                                     "ME",
	"Montserrat":                                     "MS",
	"Morocco":                                        "MA",
	"Mozambique":                                     "MZ",
	"Myanmar":                                        "MM",
	"Namibia":                                        "NA",
	"Nepal":                                          "NP",
	"Netherlands":                                    "NL",
	"New Zealand":                                    "NZ",
	"Nicaragua":                                      "NI",
	"Nigeria":                                        "NG",
	"North Macedonia":                               "MK",
	"Macedonia":                                      "MK",
	"Norway":                                         "NO",
	"Oman":                                           "OM",
	"Pakistan":                                       "PK",
	"Panama":                                         "PA",
	"Papua New Guinea":                               "PG",
	"Paraguay":                                       "PY",
	"Peru":                                           "PE",
	"Philippines":                                    "PH",
	"Poland":                                         "PL",
	"Portugal":                                       "PT",
	"Puerto Rico":                                    "PR",
	"Qatar":                                          "QA",
	"Reunion":                                        "RE",
	"Romania":                                        "RO",
	"Russia":                                         "RU",
	"Russian Federation":                            "RU",
	"Rwanda":                                         "RW",
	"Saint Kitts and Nevis":                          "KN",
	"Saint Lucia":                                    "LC",
	"Saint Vincent and the Grenadines":               "VC",
	"San Marino":                                     "SM",
	"Saudi Arabia":                                   "SA",
	"Senegal":                                        "SN",
	"Serbia":                                         "RS",
	"Seychelles":                                     "SC",
	"Sierra Leone":                                   "SL",
	"Singapore":                                      "SG",
	"Slovakia":                                       "SK",
	"Slovenia":                                       "SI",
	"South Africa":                                   "ZA",
	"South Korea":                                    "KR",
	"Korea, Republic of":                             "KR",
	"Republic of Korea":                              "KR",
	"Spain":                                          "ES",
	"Sri Lanka":                                      "LK",
	"Suriname":                                       "SR",
	"Sweden":                                         "SE",
	"Switzerland":                                    "CH",
	"Taiwan":                                         "TW",
	"Tajikistan":                                     "TJ",
	"Tanzania":                                       "TZ",
	"Thailand":                                       "TH",
	"Trinidad and Tobago":                            "TT",
	"Tunisia":                                        "TN",
	"Turkey":                                         "TR",
	"Türkiye":                                        "TR",
	"Turks and Caicos Islands":                       "TC",
	"Uganda":                                         "UG",
	"Ukraine":                                        "UA",
	"United Arab Emirates":                           "AE",
	"United Kingdom":                                 "GB",
	"United States":                                  "US",
	"United States of America":                       "US",
	"Uruguay":                                        "UY",
	"Uzbekistan":                                     "UZ",
	"Vatican City":                                   "VA",
	"Venezuela":                                      "VE",
	"Vietnam":                                        "VN",
	"Viet Nam":                                       "VN",
	"Virgin Islands, British":                        "VG",
	"Virgin Islands, U.S.":                           "VI",
	"Yemen":                                          "YE",
	"Zambia":                                         "ZM",
	"Zimbabwe":                                       "ZW",
}
