// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/djalben/xplr-core/backend/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockCardUseCase is a mock of CardUseCase interface.
type MockCardUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCardUseCaseMockRecorder
}

// MockCardUseCaseMockRecorder is the mock recorder for MockCardUseCase.
type MockCardUseCaseMockRecorder struct {
	mock *MockCardUseCase
}

// NewMockCardUseCase creates a new mock instance.
func NewMockCardUseCase(ctrl *gomock.Controller) *MockCardUseCase {
	mock := &MockCardUseCase{ctrl: ctrl}
	mock.recorder = &MockCardUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardUseCase) EXPECT() *MockCardUseCaseMockRecorder {
	return m.recorder
}

// BuyCard mocks base method.
func (m *MockCardUseCase) BuyCard(ctx context.Context, userID domain.UUID, cardType domain.CardType, nickname string) (*domain.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuyCard", ctx, userID, cardType, nickname)
	ret0, _ := ret[0].(*domain.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuyCard indicates an expected call of BuyCard.
func (mr *MockCardUseCaseMockRecorder) BuyCard(ctx, userID, cardType, nickname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuyCard", reflect.TypeOf((*MockCardUseCase)(nil).BuyCard), ctx, userID, cardType, nickname)
}

// TopUpCard mocks base method.
func (m *MockCardUseCase) TopUpCard(ctx context.Context, userID, cardID domain.UUID, amount domain.Numeric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopUpCard", ctx, userID, cardID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// TopUpCard indicates an expected call of TopUpCard.
func (mr *MockCardUseCaseMockRecorder) TopUpCard(ctx, userID, cardID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopUpCard", reflect.TypeOf((*MockCardUseCase)(nil).TopUpCard), ctx, userID, cardID, amount)
}
